# Language used for messages in the plugin
language: en

# Message from the developer: You can safely disable this option.
# However, it allows me to have information about the use of my plugin.
# I will not publish this information, it is exclusively for me
# Reload the plugin has no effect on this property, to change, please restart the server
# Metrics by bStats
metrics: true

# Heads textures
# By default, use the format "default:<value> where <value> is an encoded string (see: Other-Value at https://minecraft-heads.com/)
# Support HeadDatabase plugin, use the format "hdb:<id>" where <id> is the id of the head
# Support player head, use the format "player:<playername>" where <playername> is the name of a player
heads:
  - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWQ5Y2M1OGFkMjVhMWFiMTZkMzZiYjVkNmQ0OTNjOGY1ODk4YzJiZjMwMmI2NGUzMjU5MjFjNDFjMzU4NjcifX19'

# When enabling this, that will override above heads configuration
# If you want some idea for default heads textures or customize yours, you can define that below
# This configuration will not be updated on change, so if you want to add some another themes, simply follow the correct indentation and add your
# Same configurations than above head textures
# /!\ Will not update heads already placed /!\
headsTheme:
  enabled: false
  selected: "Christmas"
  theme:
    Easter:
      - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWIzZTAzNjM5OTIyYTUxZjI2OGU4NTZmYmIwZGQ0YzE5ZDIwNjg3OGIxY2U2YjVhZGRjNmI5ZjhmNDJmYWRjZCJ9fX0='
      - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTRkYWU1MDc2NTcyZmMzMWNmYzdmY2RhMGZkNWI3ZWJmNGFlMWQ1NmE5YjYyNWJkNTU2ZGYxZjA5NWU5YTc3ZiJ9fX0='
      - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDdmODUxOWNjNWE2MjQzZDg1ODk0OWE2YzU3MzlkY2U4NWE3NjE5YWQwZTcxYzUzNzAxYzgwZDQ3NjA0NmEwMCJ9fX0='
      - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjc5ODNmYjQ5NWQzODJmOWQ4NzgyNjBkZTk5ZTRlNmNlY2Y2MThiNjdhM2I1YzIwNTFlM2ZhZDJiNjliIn19fQ=='
      - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzA0OTY2MmEzMzY1MzNlZDY0YTExODI2NjVmZTZiMWU2YjUwYWM2ZGI3ZTk2YWE2NmY4NDcxNjhmYjkzNzI0OCJ9fX0='
      - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWViMzM1MTgyZGI1ZjNiZTgwZmNjZjZlYWJlNTk5ZjQxMDdkNGZmMGU5ZjQ0ZjM0MTc0Y2VmYTZlMmI1NzY4In19fQ=='
      - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTYyODUzMWViNWYwNTY5ZWRhZTE2YzhhNDNlYjIyZWVjZjdjMTUyMzViODM1YWUxNDE0YzI2OWNhZDEyY2E3In19fQ=='
    Halloween:
      - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDhhMzhiZjkyZDA0OGEzNzNjMGM3Y2Q5YjgzYTQ4YTdmOTgwZWU2NTU1ZTg1NDg3N2IzMmZlZjI2YTE5MzEzNiJ9fX0='
      - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjYyZWE5N2NlN2FhNzlkNGY5YzI3ODA1N2FmYTFhMWRlZTIzNjlhNDBhZjFlYTBjNTU5Zjk2OTNiNWZiZWJjYiJ9fX0='
      - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzFlMDlmNWZjZmU0MDNlYjVkZTllMThiNWMyODQzN2JlMDllOWJkY2ZiMzRhYzRiZmM3NWU4ODFhZDlhMGRkNiJ9fX0='
      - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2Y4NGJkYjRiNmFmZDg0ZmZkNmNmNDExYzgzNGQ4NDU4YzdlNTEzMTYwZDc5MjM4OThkNDljNmFmNzJmMjJjMSJ9fX0='
      - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDBlMThiZTI3OWMxNzM2ODQwZmIxOTFmNTY0YzVhZDkzYzQxYTUwN2YyYzJkNzQwYjM0ZmVlMjEyZWVmMDQxNCJ9fX0='
      - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjQyNDYwNjI4ODcyNzYzN2RjMTFmOTA4NTMyZWZlMGE0ZTI5ODBmZmM1NmNlMThjNmE1ZTljYjlkYWZlMGE0MiJ9fX0='
      - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjNjNDJiN2EyZjU5ZDA3NWQyZmY1NTE2NGVmZWE2N2JhMzM3NjViZGNmMzNjYWZmNWFlODI5MGU0NzYwYmRlMyJ9fX0='
    Christmas:
      - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWUzYWQwMzllOTAzZTMwZjkwZGFhNjhjZWJmYzVjZWU3MmI1ZWQ4NGQ2MDQ0MzgyNDA5YzY3ZjM3NGQxNzMyYiJ9fX0='
      - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTA0MGIwMzg3NjU4MDM1MGRiZjgxMzMzYWVhNjk2YTZkMmYzZjdkNTE1NmZiMGNlMjU3NzEyODNkZjYwOWE5ZiJ9fX0='
      - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjRiNzhjYjhmODMyMmU3NDM0MjQyNjlhODZlZDc0MzcyY2JjMjUyYzYzMzNhYmI5NWY2ODQ5NjQzNWFhMWU2OSJ9fX0='
      - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTFmYTQ3YTc2OGI3OWU2MWQ1ZjQzZWE4N2I0Y2U4ZGNlYTFjNDM5ZmU3Njg3MWFlOTk4MTMwMDMwNzRlYzNmYiJ9fX0='
      - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTQwZGE5OWVhNDcxODkwN2YxNzE5MGViMTUzNTJjMGRhMGRlMGNlZTE4NmQ0ZmFiZjYxNThmODE5MjZhNTA0ZiJ9fX0='
      - 'default:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmRiMjRkYzI2MjYzMTY2M2JhMWUzZTMzOTg2NDUwMTNkYzVjZDIzMzFlYzliOWYzZWIyNjg1NWEwYjEwNGJhYSJ9fX0='
    Custom:
      - ''

# Database configuration
# Support MySQL, MariaDB
database:
  enable: false
  type: MySQL
  settings:
    hostname: localhost
    database: ''
    username: ''
    password: ''
    port: 3306
    ssl: false
    prefix: ''
    # Advanced connection pool settings (only for MySQL/MariaDB)
    # Most users should not need to change these
    pool:
      maxConnections: 10
      minIdleConnections: 2
      # Timeouts in seconds
      connectionTimeout: 5
      idleTimeout: 300
      maxLifetime: 1800

# Multi-server support with Redis
redis:
  enable: false
  settings:
    hostname: localhost
    database: 0
    password: ''
    port: 6379

# Progress bar customization displayed wherever the placeholder %progress% is used
progressBar:
  totalBars: 100
  symbol: '|'
  notCompletedColor: '&7'
  completedColor: '&a'

# Interactions on head click
headClick:
  # A multiline message send to the player
  # Support placeholders (%player%, %prefix%, %current%, %max%, %progress%, %headName%) & PlaceholderAPI
  # Keep [] for no message
  messages:
    - ''
    - '%prefix% &aYou found a new head! &7(%current%/%max%)'
    - ''

  # Title send to the player
  # Support placeholders (%player%, %prefix%, %current%, %max%, %progress%) & PlaceholderAPI
  title:
    enabled: false
    firstLine: ''
    subTitle: ''
    fadeIn: 0
    stay: 50
    fadeOut: 0

  # Firework fired when a player found a head
  # Keep empty 'colors' and 'fadeColors' for random colors
  # Support multiple colors (ex: 12,16,18)
  firework:
    enabled: false
    colors: [ ]
    fadeColors: [ ]
    flicker: true
    power: 0

  # Particle displayed when a player had already found the head
  particles:
    enabled: false
    alreadyOwn:
      type: VILLAGER_ANGRY
      # Colors is only for REDSTONE type
      # Support multiple colors (ex: 12,16,18)
      colors: [ ]
      amount: 1

  # Sound on head click (You can find the list of sounds here : https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html)
  # Keep empty for no sound
  sounds:
    alreadyOwn: block_note_block_didgeridoo
    notOwn: block_note_block_bell

  # A list of commands
  # Keep [] for no command
  commands:
    - "give %player% diamond"
  randomizeCommands: false
  # Run the command only if the player has enough space in inventory
  slotsRequired: -1

  # If enabled and when a head is already found, the player will be push back on click
  pushBack:
    enabled: false
    power: 1.0

# Holograms displayed above heads
# Placeholders are not supported
# DEFAULT: use Minecraft TextDisplay (simple text)
# ADVANCED: use for placeholders (require PacketEvents)
holograms:
  plugin: DEFAULT
  heightAboveHead: 0.4
  found:
    enabled: true
    lines:
      - "&a&lFound"
  notFound:
    enabled: true
    lines:
      - "&c&lNot found"
  advanced:
    foundPlaceholder: "&a&lFound"
    notFoundPlaceholder: "&c&lNot found"
    lines:
      - "%state% &7(%current%/%max%)"

# Hint system to help player finding heads
# Configurable via the command /hb options
# Distance is calculated in blocks
# Frequency, less = more frequent
# Message is displayed in actionbar, support placeholders and extra: %position%, %distance%, %arrow%
hint:
  distance: 16
  frequency: 20
  sound:
    volume: 1
    sound: BLOCK_AMETHYST_BLOCK_CHIME
  actionBarMessage: "%prefix% &aPssst, a mystery block is near! &7(%arrow%)"

# Internal settings for internal tasks
# Increase delay or reduce view distance can improve performance but decreases the quality
internalTask:
  delay: 20 # delay in ticks (1sec = 20 ticks)
  hologramParticlePlayerViewDistance: 16

# Particles floating above the head when player has not yet found it
floatingParticles:
  notFound:
    enabled: true
    type: REDSTONE
    # Colors is only for REDSTONE type
    # Support multiple colors (ex: 12,16,18)
    colors:
      - 255,0,0
      - 255,50,0
      - 255,0,50
    amount: 3
  found:
    enabled: false
    type: REDSTONE
    # Colors is only for REDSTONE type
    # Support multiple colors (ex: 12,16,18)
    colors:
      - 0,255,0
      - 50,255,0
      - 0,255,50
    amount: 3

# Spin mode, heads will spin forever
# Set linked to false will not turn heads identically
# If linked is true, the speed used is configurable above: internalTask.delay
spin:
  enabled: false
  speed: 20
  linked: true

# If true, when a Headblocks is destroyed, it will delete all player data related to it
# If false, Headblocks destroyed will remain in database. There's no purge command atm
shouldResetPlayerData: true

# If true, heads that the player has already found will be hidden
# This requires PacketEvents to be installed
# Require a server restart to apply
# /!\ WARNING: Since this feature only hides the block visually on the client side,
#     the server still maintains the physical block. Players will encounter an invisible
#     collision box (forcefield effect) where hidden heads are located. This is a
#     technical limitation that cannot be avoided. /!\
hideFoundHeads: false

# Used to cancel commands executed when clicking on the head if current headClicked is in levels of tieredRewards
preventCommandsOnTieredRewardsLevel: false

# Used to cancel messages executed when clicking on the head if current headClicked is in levels of tieredRewards
preventMessagesOnTieredRewardsLevel: false

# Disable these options can significantly increase performance
#  -> piston will prevent any piston extension interaction (extension destroying head)
#  -> water will prevent any liquid flow interaction (water destroying head)
#  -> explosion will prevent any type of explosion that can destroy the head
externalInteractions:
  piston: true
  water: true
  explosion: true

# Used to customize the %headblocks_leaderboard_<position>_custom% placeholder
# Support placeholders (PlaceholderAPI)
# IMPORTANT: Player had to reconnect or server restart to make the modification effective
placeholders:
  leaderboard:
    prefix: ""
    suffix: ""
    nickname: false

# Tiered rewards : provide a head count to trigger a reward command list
# Add the tier, then messages, commands or broadcast message which will be executed
# You can add "slotsRequired" to give the reward only if the player has enough space in inventory
tieredRewards:
  1:
    messages:
      - ''
      - '%prefix% &aYou found &e1 head&a!'
      - ''
    commands:
      - 'give %player% diamond'
  100:
    messages:
      - ''
      - '%prefix% &aYou found &6100 heads&a!'
      - ''
    commands:
      - 'give %player% diamond 100'
    broadcast:
      - ''
      - '%prefix% &6%player% &afound &6100 heads&a!!!'
      - ''
    slotsRequired: 2

gui:
  borderIcon:
    type: GRAY_STAINED_GLASS_PANE
  previousIcon:
    type: ARROW
  nextIcon:
    type: ARROW
  backIcon:
    type: SPRUCE_DOOR
  closeIcon:
    type: BARRIER