[versions]
# Minecraft & Plugins
spigot-api = "1.20.1-R0.1-SNAPSHOT"
placeholderapi = "2.11.7"
headdatabase-api = "1.3.2"
packetevents = "2.11.2"

# Libraries
jedis = "5.2.0"
hikaricp = "7.0.2"
slf4j-jdk14 = "2.0.17"
gson = "2.13.2"
commons-lang3 = "3.20.0"
nbt-api = "2.15.5"
holoeasy = "master-SNAPSHOT"

# Build Plugins
shadow = "9.3.1"
plugin-yml = "0.6.0"
run-paper = "3.0.2"

[libraries]
# Compile Only Dependencies
spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "spigot-api" }
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
headdatabase-api = { module = "com.arcaniax:HeadDatabase-API", version.ref = "headdatabase-api" }
packetevents = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetevents" }

# Implementation Dependencies
jedis = { module = "redis.clients:jedis", version.ref = "jedis" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
slf4j-jdk14 = { module = "org.slf4j:slf4j-jdk14", version.ref = "slf4j-jdk14" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
nbt-api = { module = "de.tr7zw:item-nbt-api", version.ref = "nbt-api" }
holoeasy = { module = "com.github.AerWyn81.holoeasy:holoeasy-core", version.ref = "holoeasy" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
plugin-yml = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "plugin-yml" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
