[versions]
# Minecraft & Plugins
spigot-api = "1.20.1-R0.1-SNAPSHOT"
placeholderapi = "2.11.6"
headdatabase-api = "1.3.2"
packetevents = "2.10.1"

# Libraries
jedis = "5.1.3"
hikaricp = "5.1.0"
gson = "2.11.0"
commons-lang3 = "3.12.0"
nbt-api = "2.15.3"
holoeasy = "master-SNAPSHOT"
folialib = "0.5.1"
bstats = "3.1.0"

# Build Plugins
shadow = "8.3.5"
plugin-yml = "0.6.0"
run-paper = "3.0.2"

[libraries]
# Compile Only Dependencies
spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "spigot-api" }
placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
headdatabase-api = { module = "com.arcaniax:HeadDatabase-API", version.ref = "headdatabase-api" }
packetevents = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetevents" }

# Implementation Dependencies
jedis = { module = "redis.clients:jedis", version.ref = "jedis" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
nbt-api = { module = "de.tr7zw:item-nbt-api", version.ref = "nbt-api" }
holoeasy = { module = "com.github.AerWyn81.holoeasy:holoeasy-core", version.ref = "holoeasy" }
folialib = { module = "com.tcoded:FoliaLib", version.ref = "folialib" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
plugin-yml = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "plugin-yml" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
